const SUPABASE_URL='https://rsjtbdfbtwymzmhfwmkr.supabase.co';
const SUPABASE_KEY='sb_publishable_rzKOEim4isNCAbtfe5xYfA_OWMVN28p';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const app=document.querySelector('#app');
const fmt=n=>Number(n).toFixed(1);
async function session(){return (await db.auth.getSession()).data.session}
function shell(content){app.innerHTML=`<div class="shell"><div class="brand">FatBoySchlim</div><div class="tag">Operation: weniger FatBoy.</div>${content}<div class="nav"><span>Today</span><span>Meals</span><span>Einkauf</span><span>Gym</span><span>Progress</span></div></div>`}
function authView(){shell(`<div class="card"><h2>Welcome</h2><p class="muted">Create an account or log in. Your data will sync through Supabase.</p><label>Email</label><input id="email" type="email" autocomplete="email"><label>Password</label><input id="password" type="password" autocomplete="current-password"><div class="row"><button id="login">Log in</button><button id="signup" class="secondary">Create account</button></div><p id="msg"></p></div>`);document.querySelector('#login').onclick=()=>doAuth('login');document.querySelector('#signup').onclick=()=>doAuth('signup')}
async function doAuth(mode){const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value,msg=document.querySelector('#msg');msg.textContent='Working…';let r=mode==='signup'?await db.auth.signUp({email,password}):await db.auth.signInWithPassword({email,password});if(r.error){msg.className='error';msg.textContent=r.error.message}else{msg.className='ok';msg.textContent=mode==='signup'&&!r.data.session?'Account created. Check your email if confirmation is enabled.':'Success.';if(r.data.session) dashboard()}}
async function dashboard(){const s=await session();if(!s)return authView();shell(`<button id="logout" class="secondary">Log out</button><div class="card"><h2>Weight</h2><div id="stats" class="grid"><div class="stat"><span>Current</span><b>—</b></div><div class="stat"><span>7-day avg</span><b>—</b></div></div><label>Today's weight (lb)</label><input id="weight" type="number" inputmode="decimal" step="0.1" placeholder="e.g. 214.2"><button id="saveWeight">Save weight</button><p id="weightMsg"></p></div><div class="card"><h2>Recent entries</h2><ul id="history" class="history"><li>Loading…</li></ul></div><div class="card"><h2>Coming next</h2><p class="muted">Meals • grocery planning • pantry • workouts • PRs • measurements</p></div>`);document.querySelector('#logout').onclick=async()=>{await db.auth.signOut();authView()};document.querySelector('#saveWeight').onclick=saveWeight;loadWeights()}
async function loadWeights(){const {data,error}=await db.from('weight_logs').select('id,weight_lb,logged_on').order('logged_on',{ascending:false}).limit(30);const h=document.querySelector('#history');if(error){h.innerHTML=`<li class="error">Database not ready: ${error.message}</li>`;return}if(!data.length){h.innerHTML='<li>No weight entries yet.</li>';return}h.innerHTML=data.slice(0,10).map(x=>`<li><span>${x.logged_on}</span><b>${fmt(x.weight_lb)} lb</b></li>`).join('');const recent=data.filter(x=>(Date.now()-new Date(x.logged_on+'T12:00:00').getTime())<=7*864e5);const avg=recent.reduce((a,x)=>a+Number(x.weight_lb),0)/recent.length;document.querySelector('#stats').innerHTML=`<div class="stat"><span>Current</span><b>${fmt(data[0].weight_lb)} lb</b></div><div class="stat"><span>7-day avg</span><b>${fmt(avg)} lb</b></div>`}
async function saveWeight(){const s=await session(),v=parseFloat(document.querySelector('#weight').value),m=document.querySelector('#weightMsg');if(!v){m.className='error';m.textContent='Enter a valid weight.';return}const today=new Date().toISOString().slice(0,10);const {error}=await db.from('weight_logs').upsert({user_id:s.user.id,weight_lb:v,logged_on:today},{onConflict:'user_id,logged_on'});if(error){m.className='error';m.textContent=error.message}else{m.className='ok';m.textContent='Saved.';document.querySelector('#weight').value='';loadWeights()}}
(async()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');(await session())?dashboard():authView()})();
